---

-  name: 'provision export policy'
   na_ontap_export_policy:
      hostname:         "{{ controllers[loop_policy['controller_name']]['mgmt_ip'] }}"
      username:         "{{ controllers[loop_policy['controller_name']]['username'] }}"
      password:         "{{ controllers[loop_policy['controller_name']]['password'] }}"
      https:            true
      validate_certs:   false

      vserver:          "{{ loop_policy.vserver }}"
      name:             "{{ loop_policy.name }}"
   loop:    "{{ args['policies'] }}"
   loop_control:
      loop_var:   loop_policy

-  name: 'provision export rules'
   na_ontap_export_policy_rule:
      hostname:         "{{ controllers[loop_rule['controller_name']]['mgmt_ip'] }}"
      username:         "{{ controllers[loop_rule['controller_name']]['username'] }}"
      password:         "{{ controllers[loop_rule['controller_name']]['password'] }}"
      https:            true
      validate_certs:   false

      vserver:                "{{ loop_rule.vserver }}"
      client_match:           "{{ loop_rule.client_match          | join(',') }}"
      protocol:               "{{ loop_rule.protocol              | join(',')}}"
      ro_rule:                "{{ loop_rule.ro_rule               | join(',')}}"
      rw_rule:                "{{ loop_rule.rw_rule               | join(',')}}"
      super_user_security:    "{{ loop_rule.super_user_security   | join(',')}}"
      policy_name:            "{{ loop_rule.policy_name }}"
   loop:    "{{ args.rules }}"
   loop_control:
      loop_var:      loop_rule

-  name: 'apply policy to volume'
   na_ontap_volume:
      hostname:         "{{ controllers[loop_vol['controller_name']]['mgmt_ip'] }}"
      username:         "{{ controllers[loop_vol['controller_name']]['username'] }}"
      password:         "{{ controllers[loop_vol['controller_name']]['password'] }}"
      https:            true
      validate_certs:   false

      vserver:                "{{ loop_vol.vserver }}"
      name:                   "{{ loop_vol.vol_name }}"
      policy:                 "{{ loop_vol.policy_name }}"
   loop:    "{{ args['volumes'] }}"
   loop_control:
      loop_var:      loop_vol