---
#--------------------------------------------------------------------
# Each cluster provisioned must have an entry in the 'clusters'
# dictionary.  The cluster name is the key under 'clusters'
# and will be used to determine the name of various resources to
# be provisioned (e.g. aggrs).  Therefore the name used for the
# cluster MUST be a legal name for all resources types (e.g.
# no hyphens in the name because hyphens are illegal characters for
# aggr names).  The cluster name does not need to be DNS
# resolvable because the 'mgmt_ip' is always used to communicate with
# the cluster.
#--------------------------------------------------------------------
clusters:
  Cluster01:
    mgmt_ip:          '192.168.116.150'
    username:         "{{ vault['clusters']['Cluster01']['username'] }}"
    password:         "{{ vault['clusters']['Cluster01']['password'] }}"
      